### ISSUE TITLE
Compiling Error with "CUDA_CUDA_LIBRARY"

### ISSUE THREAD

**Issue by XueCong2** [GDAOSU/vis2mesh#11]
I compiled on unbutu18.04 and didn't use docker.

I met

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_CUDA_LIBRARY (ADVANCED)
    linked by target "MVS" in directory /home/zhangshuai/lastest/ODM/SuperBuild/src/openmvs/libs/MVS

/usr/bin/ld: cannot find -lCUDA_CUDA_LIBRARY-NOTFOUND

This issue [#627 ](https://github.com/cdcseacave/openMVS/issues/627)doesn't solve my problem.

I am a relatively new to cmake, does anyone know what went wrong?

**Comment by massile** [comment]
As suggested in the linked issue, the problem seems to come from your CUDA configuration.

As a quick fix, you can disable it in the `CMakeLists.txt` for now

Change this line 
```
SET(OpenMVS_USE_CUDA ON CACHE BOOL "Enable CUDA library")
````
to this line
```
SET(OpenMVS_USE_CUDA OFF CACHE BOOL "Enable CUDA library")
````

**Comment by sxsong1207** [comment]
@massile  Thanks for your comment! Your solution should work!
