### ISSUE TITLE
How to use cam*.json for self-defined cameras?

### ISSUE THREAD

**Issue by zhu-yuefeng** [GDAOSU/vis2mesh#13]
Environments and example: all installation are done, environment configured properly, and the demo (example1.ply) can be played properly.

I have tried your interactive mode for adding new virtual views through an open3d GUI on linux. That works well. 
But I expect a more automatic pipeline, such as writing some `cam1.json` with scripts and use these json for my own dataset. When I do so, I face 
```Failed to find match for field 'x'.
Failed to find match for field 'y'.
Failed to find match for field 'x'.
*** Generation Failed ***
```
Do you have any recommendation about how I should do to use self-defined cams?

**Comment by zhu-yuefeng** [comment]
SOLUTION:

1. created an empty directory named after the *.ply file (just like in example1)
2. put your `cam1.json` in that folder
3. run `inference.py` with `--cam cam1`

In my case, the  FATAL ERROR was that my *.ply contains double-precision data, which is not handable here. Many other programs cannot handle double-precision polygen format files too. The double-precision is introduced when, in my case, converting *.pcd to *.ply through open3d functions. ONE SOLUTION for this problem is to save the pcd as ply with CloudCompare, a software for poibt cloud process. This "save as" action can be slow and unautomated, so I look forward to hearing some better alternative solution.

**Comment by sxsong1207** [comment]
Thank you for providing your solution! Appreciate it!
