### ISSUE TITLE
openmvs texturemesh dev

### ISSUE THREAD

**Issue by zhu-yuefeng** [GDAOSU/vis2mesh#17]
You mentioned not implementing texture part despite openmvs' ability. I am trying to use openmvs to recover texture for a mesh reconstructed with vis2mesh.
The obstacle is that .mva format seems to be very specific, and I failed to find a proper way to feed it into openmvs. I think the .mva file in .ply_WORK dir should serve similar to .mvs file. Is that correct?

**Comment by sxsong1207** [comment]
@zhu-yuefeng  Yes, MVA is an alternative format for OpenMVS, the internal structure is exactly same as .mvs.  You may find the io code in https://github.com/GDAOSU/openMVS_mvasupport/tree/master/libs/MVArchive
