### ISSUE TITLE
Training Pipeline Update

### ISSUE THREAD

**Issue by impaidk** [GDAOSU/vis2mesh#3]
Hello,

I'm working on a similar topic for my Master Thesis. Vis2Mesh paper has been a very good Reference to do my work. I would like to use this repo for the same. Is there a possibility that the Training Pipeline can be uploaded or shared here any time soon? This would be really helpful for my work.

Looking forward to your reply.

Thank you in advance.

**Comment by sxsong1207** [comment]
Hi @impaidk, thanks for your interest in our work.

About the training code, sorry I don't have time to well organize it. But we can provide the dirty code for you. You may need to modify it somehow. As well as our dataset.

Does it work? If you like, please leave your email address here.

**Comment by impaidk** [comment]
Yes, that would be great. This is my E-mail address devikiran.pai@alumni.fh-aachen.de, Thank you again.

**Comment by LDNN97** [comment]
Hi, @sxsong1207 

I have evaluated Vis2Mesh on my own dataset and I was quite surprised about the excellent performance of Vis2Mesh on large scenes. Thank you for your nice work! Since I am currently doing some research about surface reconstruction, I really hope I can conduct more experiments and have extension works based on Vis2Mesh. It would be pretty helpful if you can share the training pipeline and evaluation code with me. My email is cs.liudn@my.cityu.edu.hk. Many thanks in advance and looking forward to your reply.

**Comment by egorovahelene** [comment]
Hi, @sxsong1207 ! I'm also doing the research on modern surface reconstruction methods and I found you code very powerful and useful!  Could you also send me the training part to egorovahelene@gmail.com . Thanks in advance!

**Comment by sxsong1207** [comment]
Hi, @LDNN97 @egorovahelene, link sent, looking forward to your wonderful works!

**Comment by Jiangyaoyu** [comment]
Hi, @sxsong1207
I'm also doing the research on modern surface reconstruction methonds and I found that your results were very good ! Could you can share the training pipeline and evaluation code with me. My email is jiangyaoyu@stu.nxu.edu.cn.Thanks in advance and looking forward to  your reply.

**Comment by Obarads** [comment]
Hi @sxsong1207 
Thank you for your nice work and demo code! I'm researching surface reconstruction methods for scene data with a point cloud and I have an interest in your method (especially about the use of depth image on virtual views). 
Could you also send me the training part to  id115561@gmail.com? Thanks in advance!

**Comment by quicktwit** [comment]
Hi @sxsong1207 
I really appreciate the work you did in vis2mesh. This is very interesting research. I am planning to use it for my project. Is it possible to get the training part to my email address: quicktwit@gmail.com
Thanks in advance!!

**Comment by sxsong1207** [comment]
@quicktwit  @Obarads @Jiangyaoyu Link sent, sorry for the late reply

**Comment by Legend94rz** [comment]
@sxsong1207 Hi, thanks for your great work!
I'm also researching surface reconstruction methods with point cloud data, and I'm intresting with the training part.
Could you please send me the code? Here is my email: Legend94rz@gmail.com
