### ISSUE TITLE
some problems happened in Get pretrained weights and examples part

### ISSUE THREAD

**Issue by Bobkk-k** [GDAOSU/vis2mesh#6]
I have built on docker. When I want to get pretrained weights or examples, in another word, I input the code './checkpoints/get_pretrained.sh' something wrong happen. It shows that 'warning.warn...' , 'traceback...'. Can you guide me help me solve the error?

**Comment by Bobkk-k** [comment]
These are the image of the errors, thank you
![2022-03-01 22-57-59屏幕截图](https://user-images.githubusercontent.com/78141973/156197047-ed8f3c07-bd76-4c17-b484-f29d3e1142fe.png)
![2022-03-01 22-58-34屏幕截图](https://user-images.githubusercontent.com/78141973/156197069-e3fe9bbd-d612-4a30-b979-3d31c860acee.png)
![2022-03-01 22-55-32屏幕截图](https://user-images.githubusercontent.com/78141973/156197105-0ac0076e-5fb4-43d0-9cb3-cdbab907f1d0.png)

**Comment by sxsong1207** [comment]
https://drive.google.com/file/d/1cxWPWTJgMuUrbvnKp5hDmxzqCyNVV8Yd/view?usp=sharing

Could you please download it manually? It seems network issue, or google blocked your access.

**Comment by Bobkk-k** [comment]
oh, nice! But when I continue next step i.e. I run the command 'python inference.py example/example1.ply --cam cam0' , a new error rise. It shows that No such file or directory: 'vvtool'. Where is the vvtool? Is there some preparation I didn't do? Or, Is that some files I put wrong place？By the way, I have downloaded the above-mentioned file named 'VDVNet_CascadePPP_epoch30.pth' and I put it in checkpoints folder. Is that right?
![image](https://user-images.githubusercontent.com/78141973/156302764-7e043744-05c7-4f17-9166-d2a64a5126c3.png)

**Comment by Bobkk-k** [comment]
> https://drive.google.com/file/d/1cxWPWTJgMuUrbvnKp5hDmxzqCyNVV8Yd/view?usp=sharing
> 
> Could you please download it manually? It seems network issue, or google blocked your access.

**Comment by Bobkk-k** [comment]
Thanks! I solve it by downloading maually!

**Comment by sxsong1207** [comment]
Good to know its solved, thanks for your report.
