### ISSUE TITLE
How to use the last docker command 

### ISSUE THREAD

**Issue by Bobkk-k** [GDAOSU/vis2mesh#9]
Hi,

I want to ask whether the command in image  is neccesary. If neccesary, how should i use it? 

I try to input it, but an error called command not found is displayed. Sorry about I'm not good at docker.

![图片](https://user-images.githubusercontent.com/78141973/156883025-f4f058d4-2c16-450a-9bfc-ccccb43aaf55.png)

**Comment by sxsong1207** [comment]
Hi,

This is the command to launch the docker and run the program.

**Comment by Bobkk-k** [comment]
> Hi,
> 
> This is the command to launch the docker and run the program.

Hi,
I  finally made this programme work. Thank you for your reply every time. 

I want to ask you one more thing.  I 'm done running the example which has RGB information named gsm.ply , but the result is mesh which has no real RGB information. Is that a mistake or is that whai it looks like?

**Comment by Bobkk-k** [comment]
> > Hi,
> > This is the command to launch the docker and run the program.
> 
> Hi, I finally made this programme work. Thank you for your reply every time.
> 
> I want to ask you one more thing. I 'm done running the example which has RGB information named gsm.ply , but the result is mesh which has no real RGB information. Is that a mistake or is that whai it looks like?
